# Jekyll конфигурация для CryptoWatch MEXC
title: "CryptoWatch MEXC"
description: "Профессиональный Telegram-бот для мониторинга ценовых движений на бирже MEXC с техническим анализом и умными сигналами"
baseurl: "/CryptoWatch-MEXC"
url: "https://pozitive007.github.io"

# Автор и контактная информация
author:
  name: "CryptoWatch Team"
  email: "support@cryptowatch-mexc.com"
  telegram: "@Solnyshchko"

# SEO настройки
lang: "ru"
timezone: "Europe/Moscow"

# Jekyll настройки
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Настройки сборки
sass:
  sass_dir: css
  style: compressed

# Исключения из сборки
exclude:
  - node_modules
  - package.json
  - README.md
  - .gitignore
  - simple_server.py
  - start_server.bat

# Параметры сайта
telegram_bot: "https://t.me/DUMPBest_bot"
support_contact: "https://t.me/Solnyshchko"
boosty_link: "https://boosty.to/cryptowatch-mexc"

# Социальные сети
social:
  telegram: "https://t.me/DUMPBest_bot"
  twitter: "https://twitter.com/cryptowatch_mexc"
  discord: "https://discord.gg/cryptowatch"

# Конфигурация аналитики
analytics:
  google_id: null  # Добавить при необходимости
  yandex_id: null  # Добавить при необходимости

# Настройки производительности
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Дополнительные оптимизации
future: false
show_drafts: false
limit_posts: 10

# Конфигурация кэширования
incremental: true

# Плагины для оптимизации
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gzip

# Настройки gzip
gzip:
  extensions: 
    - .html
    - .css
    - .js
    - .xml
    - .txt
